---

version: '3'

services:
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    image: hexletbasics/services-app:cached
    command: "make ci-check"
    depends_on:
      - postgres

  # production:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.production
  #   env_file:
  #     - .env

    depends_on:
      - postgres

volumes:
  pgdata:
